export const SELECT_QUIZ_START ='SELECT_QUIZ_START';
export const SELECT_QUIZ_ERROR ='SELECT_QUIZ_ERROR';
export const SELECT_QUIZ_COMPLETE ='SELECT_QUIZ_COMPLETE';

export const SELECT_QUIZ_BY_ID_START = 'SELECT_QUIZ_BY_ID_START';
export const SELECT_QUIZ_BY_ID_ERROR = 'SELECT_QUIZ_BY_ID_ERROR';
export const SELECT_QUIZ_BY_ID_COMPLETE = 'SELECT_QUIZ_BY_ID_COMPLETE';